### ISSUE TITLE
not loading

### ISSUE THREAD

**Issue by Melkor82** [gurbyz/custom-cards-lovelace#14]
I get this error when loading
`power-wheel-card.js?v=1:7:27 Uncaught TypeError: Cannot convert undefined or null to object`

**Comment by gurbyz** [comment]
Pls supply all the requested data when reporting an issue. Otherwise I’m not able to help you. Did you maybe delete the complete issue template by accident?

**Comment by Melkor82** [comment]
ops sorry i pushed open regular issue instead of the get started button. Can i delete this one and create a proper issue?

**Comment by gurbyz** [comment]
Yes, you could. :-)
