### ISSUE TITLE
custom-cards org

### ISSUE THREAD

**Issue by iantrich** [gurbyz/custom-cards-lovelace#19]
Invitation to bring your repo over to the community custom-cards organization: https://github.com/custom-cards/information

Let me know if you're interested and I can float you an invitation to the org. Thanks!

**Comment by gurbyz** [comment]
Nice initiative! I'm not sure if my repo structure complies to the requirements. But I have the info file present for the first card in my repo:
https://raw.githubusercontent.com/gurbyz/custom-cards-lovelace/master/custom_updater.json

**Comment by gurbyz** [comment]
Haven't heard from you in a while. I'm closing the issue.
